controller_manager:
    ros__parameters:

        update_rate: 20 # Hz

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        joint_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        forward_velocity_controller:
            type: velocity_controllers/JointGroupVelocityController

        forward_position_controller:
            type: position_controllers/JointGroupPositionController


joint_trajectory_controller:
    ros__parameters:
        joints:
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
        command_interfaces:
            - position
            # - velocity
        state_interfaces:
            - position
            - velocity
        state_publish_rate: 20.0
        action_monitor_rate: 20.0

forward_velocity_controller:
    ros__parameters:
        joints:
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
        interface_name: velocity

forward_position_controller:
    ros__parameters:
        joints:
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
            - joint6
        interface_name: position
