controller_manager:
    ros__parameters:

        update_rate: 20 # Hz

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        joint_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        forward_velocity_controller:
            type: velocity_controllers/JointGroupVelocityController

        forward_position_controller:
            type: position_controllers/JointGroupPositionController

joint_trajectory_controller:
    ros__parameters:
        joints:
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity
        state_publish_rate: 20.0
        action_monitor_rate: 20.0
        allow_partial_joints_goal: false
        constraints:
            stopped_velocity_tolerance: 0.2
            goal_time: 10.0
            joint0: { trajectory: 0.5, goal: 0.2 }
            joint1: { trajectory: 0.5, goal: 0.2 }
            joint2: { trajectory: 0.5, goal: 0.2 }
            joint3: { trajectory: 0.5, goal: 0.2 }
            joint4: { trajectory: 0.5, goal: 0.2 }
            joint5: { trajectory: 0.5, goal: 0.2 }


forward_velocity_controller:
    ros__parameters:
        joints:
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
        interface_name: velocity

forward_position_controller:
    ros__parameters:
        joints:
            - joint0
            - joint1
            - joint2
            - joint3
            - joint4
            - joint5
        interface_name: position
