mesh_files:
  body_base:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri5sdual/visual/Nuri5sdual_base.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri5sdual/collision/Nuri5sdual_base.stl

  # left arm
  left_arm_link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_0.stl
  left_arm_link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_1.stl
  left_arm_link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_2.stl
  left_arm_link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_3.stl
  left_arm_link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_4.stl
  left_arm_link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_5.stl
  left_arm_link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_6.stl

  # right arm
  right_arm_link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_0.stl
  right_arm_link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_1.stl
  right_arm_link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_2.stl
  right_arm_link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_3.stl
  right_arm_link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_4.stl
  right_arm_link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_5.stl
  right_arm_link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri4s/visual/Nuri4s_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri4s/collision/Nuri4s_6.stl
