controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_joint0
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      left_arm_joint0: {trajectory: 0.2, goal: 0.1}
      left_arm_joint1: {trajectory: 0.2, goal: 0.1}
      left_arm_joint2: {trajectory: 0.2, goal: 0.1}
      left_arm_joint3: {trajectory: 0.2, goal: 0.1}
      left_arm_joint4: {trajectory: 0.2, goal: 0.1}
      left_arm_joint5: {trajectory: 0.2, goal: 0.1}

right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_joint0
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      right_arm_joint0: {trajectory: 0.2, goal: 0.1}
      right_arm_joint1: {trajectory: 0.2, goal: 0.1}
      right_arm_joint2: {trajectory: 0.2, goal: 0.1}
      right_arm_joint3: {trajectory: 0.2, goal: 0.1}
      right_arm_joint4: {trajectory: 0.2, goal: 0.1}
      right_arm_joint5: {trajectory: 0.2, goal: 0.1}
