# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import EtherCATCommgRPCServer_pb2 as EtherCATCommgRPCServer__pb2


class GRPCECatTaskStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMasterStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMasterStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetSlaveStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetSlaveStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                )
        self.GetRxDomainStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetRxDomainStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetTxDomainStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetTxDomainStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.IsSystemReady = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/IsSystemReady',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                )
        self.SetServoOnOff = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetServoOnOff',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoIndex.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetRxPDOMotorDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetRxPDOMotorDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.MotorDriverRxIndex.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetRxPDOMotorDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetRxPDOMotorDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.MotorDriverRx.FromString,
                )
        self.GetTxPDOMotorDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetTxPDOMotorDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.MotorDriverTx.FromString,
                )
        self.SetRxPDOPanasonicDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetRxPDOPanasonicDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.PanasonicDriverRxIndex.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetTxPDOPanasonicDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetTxPDOPanasonicDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.PanasonicDriverTx.FromString,
                )
        self.SetNRMKIOBoardOutput = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetNRMKIOBoardOutput',
                request_serializer=EtherCATCommgRPCServer__pb2.IOBoardRx.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetNRMKIOBoardInput = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetNRMKIOBoardInput',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IOBoardTx.FromString,
                )
        self.GetNRMKIOBoardOutput = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetNRMKIOBoardOutput',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IOBoardRx.FromString,
                )
        self.GetRobotusFTSensor = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetRobotusFTSensor',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.RobotusFTTx.FromString,
                )
        self.ResetWelconDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/ResetWelconDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetErrorCode = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetErrorCode',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetCORETemperature1 = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCORETemperature1',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.FloatVal.FromString,
                )
        self.GetCORETemperature2 = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCORETemperature2',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.FloatVal.FromString,
                )
        self.GetCORETemperature3 = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCORETemperature3',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.FloatVal.FromString,
                )
        self.GetMaxTorque = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMaxTorque',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetProfileVelocity = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetProfileVelocity',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetProfileAcc = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetProfileAcc',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetProfileDec = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetProfileDec',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.SetMaxTorque = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetMaxTorque',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetProfileVelocity = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetProfileVelocity',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetProfileAcc = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetProfileAcc',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetProfileDec = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetProfileDec',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )


class GRPCECatTaskServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMasterStatus(self, request, context):
        """Master and slave status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSlaveStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRxDomainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxDomainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsSystemReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServoOnOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRxPDOMotorDriver(self, request, context):
        """Read and Write PDOs (Motor Driver)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRxPDOMotorDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxPDOMotorDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRxPDOPanasonicDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxPDOPanasonicDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNRMKIOBoardOutput(self, request, context):
        """Read and Write PDOs (Neuromeka IO board)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNRMKIOBoardInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNRMKIOBoardOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotusFTSensor(self, request, context):
        """Read and Write PDOs (Beckhoff)
        Read and Write PDOs (Robotus FT sensor)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetWelconDriver(self, request, context):
        """Motor drive control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorCode(self, request, context):
        """Read and Write SDOs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCORETemperature1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCORETemperature2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCORETemperature3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaxTorque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileAcc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileDec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaxTorque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileAcc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileDec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCECatTaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMasterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMasterStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetSlaveStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSlaveStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            ),
            'GetRxDomainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRxDomainStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetTxDomainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxDomainStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'IsSystemReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSystemReady,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            ),
            'SetServoOnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServoOnOff,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoIndex.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetRxPDOMotorDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRxPDOMotorDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.MotorDriverRxIndex.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetRxPDOMotorDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRxPDOMotorDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.MotorDriverRx.SerializeToString,
            ),
            'GetTxPDOMotorDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxPDOMotorDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.MotorDriverTx.SerializeToString,
            ),
            'SetRxPDOPanasonicDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRxPDOPanasonicDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.PanasonicDriverRxIndex.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetTxPDOPanasonicDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxPDOPanasonicDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.PanasonicDriverTx.SerializeToString,
            ),
            'SetNRMKIOBoardOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNRMKIOBoardOutput,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IOBoardRx.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetNRMKIOBoardInput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNRMKIOBoardInput,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IOBoardTx.SerializeToString,
            ),
            'GetNRMKIOBoardOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNRMKIOBoardOutput,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IOBoardRx.SerializeToString,
            ),
            'GetRobotusFTSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotusFTSensor,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.RobotusFTTx.SerializeToString,
            ),
            'ResetWelconDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetWelconDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetErrorCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorCode,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetCORETemperature1': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCORETemperature1,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.FloatVal.SerializeToString,
            ),
            'GetCORETemperature2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCORETemperature2,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.FloatVal.SerializeToString,
            ),
            'GetCORETemperature3': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCORETemperature3,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.FloatVal.SerializeToString,
            ),
            'GetMaxTorque': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaxTorque,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetProfileVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileVelocity,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetProfileAcc': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileAcc,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetProfileDec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileDec,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'SetMaxTorque': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaxTorque,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetProfileVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileVelocity,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetProfileAcc': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileAcc,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetProfileDec': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileDec,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCECat.GRPCECatTask', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCECatTask(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMasterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMasterStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSlaveStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetSlaveStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVals.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRxDomainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetRxDomainStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTxDomainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetTxDomainStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsSystemReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/IsSystemReady',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVals.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetServoOnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetServoOnOff',
            EtherCATCommgRPCServer__pb2.ServoIndex.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRxPDOMotorDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetRxPDOMotorDriver',
            EtherCATCommgRPCServer__pb2.MotorDriverRxIndex.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRxPDOMotorDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetRxPDOMotorDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.MotorDriverRx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTxPDOMotorDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetTxPDOMotorDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.MotorDriverTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRxPDOPanasonicDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetRxPDOPanasonicDriver',
            EtherCATCommgRPCServer__pb2.PanasonicDriverRxIndex.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTxPDOPanasonicDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetTxPDOPanasonicDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.PanasonicDriverTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNRMKIOBoardOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetNRMKIOBoardOutput',
            EtherCATCommgRPCServer__pb2.IOBoardRx.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNRMKIOBoardInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetNRMKIOBoardInput',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IOBoardTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNRMKIOBoardOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetNRMKIOBoardOutput',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IOBoardRx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotusFTSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetRobotusFTSensor',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.RobotusFTTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetWelconDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/ResetWelconDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetErrorCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetErrorCode',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCORETemperature1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCORETemperature1',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.FloatVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCORETemperature2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCORETemperature2',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.FloatVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCORETemperature3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCORETemperature3',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.FloatVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaxTorque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMaxTorque',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetProfileVelocity',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileAcc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetProfileAcc',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileDec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetProfileDec',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMaxTorque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetMaxTorque',
            EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetProfileVelocity',
            EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileAcc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetProfileAcc',
            EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileDec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetProfileDec',
            EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
