# Values converted from the supplied S50 URDF radians to degrees.
joint_limits:
  joint0:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 200
    max_velocity: !degrees 90.0
    max_position: !degrees 360.0
    min_position: !degrees -360.0
    damping: 10.0
    friction: 10.0
  joint1:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 350
    max_velocity: !degrees 90.0
    max_position: !degrees 10.0
    min_position: !degrees -190.0
    damping: 40.0
    friction: 40.0
  joint2:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 200
    max_velocity: !degrees 90.0
    max_position: !degrees 168.0
    min_position: !degrees -168.0
    damping: 10.0
    friction: 10.0
  joint3:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 104
    max_velocity: !degrees 90.0
    max_position: !degrees 360.0
    min_position: !degrees -360.0
    damping: 10.0
    friction: 10.0
  joint4:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 34
    max_velocity: !degrees 90.0
    max_position: !degrees 360.0
    min_position: !degrees -360.0
    damping: 10.0
    friction: 10.0
  joint5:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 34
    max_velocity: !degrees 90.0
    max_position: !degrees 360.0
    min_position: !degrees -360.0
    damping: 10.0
    friction: 10.0
