# How links connect together
kinematics:
  joint0:
    x: -0.00095358
    y: 0.00029783
    z: 0.0425
    roll: 0
    pitch: 0
    yaw: 0
  joint1:
    x: 0
    y: -0.0735
    z: 0.1645
    roll: -1.5708
    pitch: 0
    yaw: 0
  joint2:
    x: 0
    y: -0.29
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  joint3:
    x: 0
    y: -0.147
    z: 0.0735
    roll: 1.5708
    pitch: 0
    yaw: 0
  joint4:
    x: 0
    y: 0.05
    z: 0.193
    roll: 0
    pitch: 0
    yaw: 0
  joint5:
    x: -0.00063227
    y: -0.05
    z: 0.065495
    roll: 0
    pitch: 0
    yaw: 0
  tcp:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
