mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/opti3/visual/Opti3_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/opti3/collision/Opti3_6.stl
