joint_axes:
  Joint_L0: [0, 0, 1]
  Joint_L1: [0, 0, -1]
  Joint_L2_U: [0, 0, -1]
  Joint_L3_U: [0, 0, 1]
  Joint_L2_L: [0, 0, 1]
  Joint_L3_L: [0, -1, 0]
  Joint_L4_L: [0, 0, 1]
  Joint_L5_L: [0, -1, 0]
  Joint_L6_L: [0, 0, 1]
  Joint_L7_L: [0, -1, 0]
  Joint_L8_L: [1, 0, 0]
  Joint_L2_R: [0, 0, 1]
  Joint_L3_R: [0, 1, 0]
  Joint_L4_R: [0, 0, 1]
  Joint_L5_R: [0, 1, 0]
  Joint_L6_R: [0, 0, 1]
  Joint_L7_R: [0, 1, 0]
  Joint_L8_R: [-1, 0, 0]
  right_gripper_finger1_joint: [0, -1, 0]
  right_gripper_finger2_joint: [0, -1, 0]
  right_gripper_finger1_finger_joint: [0, -1, 0]
  right_gripper_finger2_finger_joint: [0, -1, 0]
  right_gripper_finger1_inner_knuckle_joint: [0, -1, 0]
  right_gripper_finger2_inner_knuckle_joint: [0, -1, 0]
  right_gripper_finger1_finger_tip_joint: [0, 1, 0]
  right_gripper_finger2_finger_tip_joint: [0, 1, 0]
  left_gripper_finger1_joint: [0, -1, 0]
  left_gripper_finger2_joint: [0, -1, 0]
  left_gripper_finger1_finger_joint: [0, -1, 0]
  left_gripper_finger2_finger_joint: [0, -1, 0]
  left_gripper_finger1_inner_knuckle_joint: [0, -1, 0]
  left_gripper_finger2_inner_knuckle_joint: [0, -1, 0]
  left_gripper_finger1_finger_tip_joint: [0, 1, 0]
  left_gripper_finger2_finger_tip_joint: [0, 1, 0]
