# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import ros_interface_pb2 as ros__interface__pb2


class IndyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetJointPos = channel.unary_unary(
        '/IndyRosInterface.IndyService/GetJointPos',
        request_serializer=ros__interface__pb2.Empty.SerializeToString,
        response_deserializer=ros__interface__pb2.JointPosRes.FromString,
        )
    self.GetRobotState = channel.unary_unary(
        '/IndyRosInterface.IndyService/GetRobotState',
        request_serializer=ros__interface__pb2.Empty.SerializeToString,
        response_deserializer=ros__interface__pb2.RobotStateRes.FromString,
        )
    self.SetJointVelocityLevel = channel.unary_unary(
        '/IndyRosInterface.IndyService/SetJointVelocityLevel',
        request_serializer=ros__interface__pb2.JointVelocityLevelReq.SerializeToString,
        response_deserializer=ros__interface__pb2.Empty.FromString,
        )
    self.SetJointBlending = channel.unary_unary(
        '/IndyRosInterface.IndyService/SetJointBlending',
        request_serializer=ros__interface__pb2.JointBlendingReq.SerializeToString,
        response_deserializer=ros__interface__pb2.Empty.FromString,
        )
    self.MoveJoint = channel.unary_unary(
        '/IndyRosInterface.IndyService/MoveJoint',
        request_serializer=ros__interface__pb2.MoveJointReq.SerializeToString,
        response_deserializer=ros__interface__pb2.Empty.FromString,
        )
    self.MoveJointWaypoint = channel.unary_unary(
        '/IndyRosInterface.IndyService/MoveJointWaypoint',
        request_serializer=ros__interface__pb2.MoveJointWaypointReq.SerializeToString,
        response_deserializer=ros__interface__pb2.Empty.FromString,
        )
    self.StopRobot = channel.unary_unary(
        '/IndyRosInterface.IndyService/StopRobot',
        request_serializer=ros__interface__pb2.Empty.SerializeToString,
        response_deserializer=ros__interface__pb2.Empty.FromString,
        )


class IndyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetJointPos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRobotState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetJointVelocityLevel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetJointBlending(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveJoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveJointWaypoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopRobot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IndyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetJointPos': grpc.unary_unary_rpc_method_handler(
          servicer.GetJointPos,
          request_deserializer=ros__interface__pb2.Empty.FromString,
          response_serializer=ros__interface__pb2.JointPosRes.SerializeToString,
      ),
      'GetRobotState': grpc.unary_unary_rpc_method_handler(
          servicer.GetRobotState,
          request_deserializer=ros__interface__pb2.Empty.FromString,
          response_serializer=ros__interface__pb2.RobotStateRes.SerializeToString,
      ),
      'SetJointVelocityLevel': grpc.unary_unary_rpc_method_handler(
          servicer.SetJointVelocityLevel,
          request_deserializer=ros__interface__pb2.JointVelocityLevelReq.FromString,
          response_serializer=ros__interface__pb2.Empty.SerializeToString,
      ),
      'SetJointBlending': grpc.unary_unary_rpc_method_handler(
          servicer.SetJointBlending,
          request_deserializer=ros__interface__pb2.JointBlendingReq.FromString,
          response_serializer=ros__interface__pb2.Empty.SerializeToString,
      ),
      'MoveJoint': grpc.unary_unary_rpc_method_handler(
          servicer.MoveJoint,
          request_deserializer=ros__interface__pb2.MoveJointReq.FromString,
          response_serializer=ros__interface__pb2.Empty.SerializeToString,
      ),
      'MoveJointWaypoint': grpc.unary_unary_rpc_method_handler(
          servicer.MoveJointWaypoint,
          request_deserializer=ros__interface__pb2.MoveJointWaypointReq.FromString,
          response_serializer=ros__interface__pb2.Empty.SerializeToString,
      ),
      'StopRobot': grpc.unary_unary_rpc_method_handler(
          servicer.StopRobot,
          request_deserializer=ros__interface__pb2.Empty.FromString,
          response_serializer=ros__interface__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IndyRosInterface.IndyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
